spring:
  application:
    name: project
  data:
    mongodb:
      uri: ${MONGO_DB_URI}
      auto-index-creation: true

server:
  port: 8082

logging:
  level.com.spring.project: debug

api:
  keys:
    weather: ${WEATHER_API_KEY}
    quotes: ${QUOTES_API_KEY}
