spring:
  application:
    name: project
  data:
    mongodb:
      uri: ${MONGO_DB_URI}
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
  mail:
    port: 587
    username: divyeshjivani10@gmail.com
    password: ${EMAIL_PASSWORD}
    host: smtp.gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8082

api:
  keys:
    weather: ${WEATHER_API_KEY}
    quotes: ${QUOTES_API_KEY}
